- .github/workflows/build.yml
- configure.ac
- src/Makefile.am
- src/debug.c
- tests/Makefile.am
- tests/openssl.cnf.in
Includes fixes to make this work:
- some changes to configure to account for differences in debian/ubuntu packaging of NSS
- some fixes for breakage I caused when pushed a barely tested rename earlier.
- some unexpected segfaults as apparently for loops variables are initialized to 0 in Fedora but not in Debian, probably different default flags between the two.
> Add minimal CI via github actions

- src/asymmetric_cipher.c
- src/exchange.c
- src/kdf.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- src/util.c
This allow OpenSSL application to see and return more meaningful errors directly returned from the provider.
> Add support to return errors to OpenSSL

- src/keys.c
- src/store.c
As reported by clang, the & has lower precedence than == operator.
Use parentheses as needed when checking for a set bit.
> Fix operator precedence errors

- src/keymgmt.c
The branching in p11prov_rsakm_secbits() has missed the 2048 value
because of < 2048 and > 2048 checks.  Fix the off-by-one check.
> Fix logical error in p11prov_rsakm_secbits

- src/Makefile.am
The automake needs to know what files are part of the distribution
when making distribution tarball and to calculate the dependencies.
Add all used headers to the pkcs11_provider_la_SOURCES.
> Add headers to the Makefile.am

- .gitignore
- src/Makefile.am
- src/platform/endian.h
- src/store.c
The <endian.h> isn't POSIX, add a compatibility shim (taken and
relicensed from BIND 9) to support various BSDs and macOS systems.
> Add compatibility shim for endian related functions

- src/provider.c
The RTLD_DEEPBIND flag is not present on all platforms.  Use it only if
it's present on the platform.
> Make RTLD_DEEPBIND optional

- src/store.c
Some compilers (clang) complain when CK_UTF8CHAR_PTR is passed to
const char * argument because char might or might not be signed
depending on the platform.  Properly cast the values to silence
the warnings.
> Fix mismatch between CK_UTF8CHAR_PTR and const char *

- .clang-format
- .clang-format-ignore
- .github/workflows/style.yml
- .reuse/dep5
- Makefile.am
- src/asymmetric_cipher.c
- src/debug.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/keys.c
- src/pkcs11.h
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- src/util.c
This is an initial example of how .clang-format can be configured. It doesn't precisely match the current style, but no tool can do that.
> Add initial .clang-format style and reformat the sources using it

- .github/workflows/build.yml
- .github/workflows/style.yml
- .reuse/dep5
- BUILD.md
- configure.ac
Add a BUILD.md file to start documenting build process and requirements
Fixes #18
> Add checks to enforce at least c11 semantics

- .github/workflows/scan-build.yml
Run scan-build on any new pull request. Save the report in case of bugs
found.
> Add GitHub Action that runs Clang's scan-build

- src/asymmetric_cipher.c
- src/exchange.c
- src/signature.c
The OPENSSL_strcasecmp() uses "C" locale for case insensitive comparison
in POSIX-compatible system and on Windows.
Signed-off-by: Ondřej Surý <ondrej@sury.org>
> Use OPENSSL_strcasecmp() instead of strcasecmp()

- .github/workflows/style.yml
- .gitignore
- src/asymmetric_cipher.c
- src/debug.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/keys.c
- src/provider.c
- src/signature.c
- src/store.c
- src/util.c
As the clang-format doesn't have (yet) the capability to add braces around single read statements, clang-tidy needs to be used for this.
> Add missing single-line braces using clang-tidy

- .github/workflows/build.yml
The LLVM/Clang has different checks, so it's often useful to compile the project also with non-GCC compiler.
> Add GitHub Action to build with clang

- configure.ac
- src/Makefile.am
- src/asymmetric_cipher.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/keys.c
- src/provider.c
- src/signature.c
- src/store.c
- src/util.c
Enable -Wall -Wextra and couple of additional warnings and treat
them as errors.
Because the implementation is not complete, disable unused parameter
warning.
And fix all issues found.
> Enable all (most) of the warnings as errors

- .github/workflows/coverity-scan.yml
This requires setting two secrets, but I've tested it on my fork, and it works as it should.
> Add GitHub Action for Coverity Scan

- .clang-format
- src/asymmetric_cipher.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- src/util.c
This allows to load multiple objects (currently only keys) and enumerate
them all.
Note: We need to store the login_session on the provider context because
otherwise we can't guarantee the token is "logged in" for the duration
of operations on private key later on.
We could create a session object and take a refeence on key that come
from logged in slots, but will leave that for later.
Issue that had to be wroked around: the password callback.
I used it to allow interactive pin usage, but the callabcks are only passed
to the _load() function.
Therefore we need code to defer loading or retry loading if a login was
required (basically always for private keys).
May be a bug to open with OpenSSL, UI pin callbacks should be provided
also at store open.
Fixes #37
> Allow store to enumerate objects

- src/pkcs11.h
The OASIS versions of PKCS#11 specification made incompatible
change to the specification. It is still defacto standard to
not use structure packing on Linux.
Signed-off-by: Timo Teräs <timo.teras@iki.fi>
> Clarfiy PKCS#11 structure packing comment

- src/keys.c
- src/provider.h
- src/store.c
No need to open a new session in find_keys when we already have
one on the store context.
> Make use of the session stored on the store ctx

- src/kdf.c
- src/keys.c
- src/provider.h
- src/store.c
- src/util.c
- tests/test.sh
This happened while testing with an incorrect pkcs11_uri, the code now
always initialized ctx->loaded to an invalid value on unrecoverable
errors and causes the store load to properly fail.
> Fix infinite loop in case no key was found.

- src/asymmetric_cipher.c
- src/exchange.c
- src/keymgmt.c
- src/keys.c
- src/provider.h
- src/signature.c
- src/store.c
- tests/test.sh
Always load all keys in the token when the store is queried.
Store only one key per p11prov_obj, prepare it to contain other object types in the future.
> Key loading

- tests/Makefile.am
The test would fail if softokn has wrong path detected. It is required
just for testing, not a normal build. Add a simple check to makefile to
indicate a working path is expected.
> Fail hard make check if nss-softokn devel files were not found

- src/debug.c
Last PR ended up adding a zero byte after each newline character in
error.
> Debug: remove zero bytes after newlines

- .gitignore
- Makefile.am
- src/Makefile.am
- tests/Makefile.am
As I started to work with the project, I realized some missing git ignore patterns and files the base automake targets. This series contains some fixes for these issues.
I decided to split my changes into multiple commits, just to make it more clear, what I've changed. But I'm open to merge some of them, if you prefer it.
> fixes for git, autotools and library lookup

- src/asymmetric_cipher.c
- src/debug.c
- src/exchange.c
- src/kdf.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- src/util.c
Change this function to be a status check function that can optionally
return  a functions pointer.
This will make the error reutrned consistent and will be used generally
to check the status of the provider before even initializing new
functions so that error conditions can be returned early.
> Repurpose p11prov_ctx_fns as status check function

- .gitignore
- src/Makefile.am
- src/asymmetric_cipher.c
- src/exchange.c
- src/kdf.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/session.c
- src/signature.c
- src/store.c
- src/util.c
- tests/Makefile.am
- tests/test.sh
- tests/tsession.c
This PR implement a session object as well as pooling of session objects.
The design reuses allocated objects to minimize memory allocation on reuse, it also permits referencing of session objects multiple times. No code uses this currently but I can see it done when the code currently tries to duplicate sessions perhaps. This is a detail that will need discussion.
freeing a session object causes locking to be used in order to move a session object from the busy_sessions list to the free_sessions list. This is something we may want to avoid, so needs discussion.
Fixes #32
> Session object pooling

- src/keys.c
- src/session.c
Once again coverity unveils real errors w/o false positives.
Yay!
> Coverity Fixes 4

- .gitignore
- src/Makefile.am
- src/asymmetric_cipher.c
- src/encoder.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/keys.c
- src/platform/endian.h
- src/provider.c
- src/provider.h
- src/session.c
- src/signature.c
- src/store.c
- src/util.c
- tests/Makefile.am
- tests/tgenkey.c
Try to implement RSA key generation function as best we can.
openssl genpkey assumes that you *always* have key data to return, which is obviously not the case when generateing a key on a token.
We provide a function to print the -text option, but errors are reported from the missing pem/der encoding functions although public and private keys are generated and stored in the DB.
A separate test binary checks that we can correctly generate keys and apply ID and Label to them.
> Rsa keygen

- src/keys.c
- src/provider.h
- src/util.c
The key objects can also be referenced by label. According to RFC 7512 the "object=<value>" is related to the label attribute of the key object. Introduce a label attribute to the URI struct and use it to find the key objects.
Signed-off-by: Holger Dengler <dengler@linux.ibm.com>
> uri: fix key references by label

- src/asymmetric_cipher.c
- src/encoder.c
- src/exchange.c
- src/keymgmt.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- src/util.c
- tests/tgenkey.c
Fixes #60 
Also fixes an off by one bug in the store.
Not all parameters can be handled, and even those we can most tokens will not be able to for now.
> Add RSA-PSS support

- .github/workflows/style.yml
- BUILD.md
- CONTRIBUTING.md
- src/exchange.c
- src/kdf.c
- src/keys.c
- src/provider.c
- src/session.c
- src/signature.c
- src/store.c
- src/util.c
- tests/README
- tests/test.sh
Avoid retaining and introducing more spelling mistakes
> Add codespell to CI

- src/debug.c
This was causing unecessary empty lines and increasing the rendered size of debug output.
> Remove double newlines in some debug functions

- src/store.c
This does not lead to a crash because sessions are cached and reused, but can cause issues (beyond nasty "possible double free" messages), as it may free a session reused by another thread while it is in use.
Related #66
> Avoid leaving behind a freed pointer

- src/session.c
- src/store.c
Rework p11prov_get_session()/store_load to be very clear on one shot, vs iterative lookup.
Fixes #66
> Improve store loading with multiple tokens

- configure.ac
- src/provider.c
Configuration of the provider through the openssl configuration file is cumbersome and it prevents also dynamically loading the provider (or makes it very complicated, see openssl/openssl#19496). Especially for testing, it would be very useful to have a way to pass environment variable with the testing pkcs11 module to use.
For generic use and integration in the consistent pkcs11 in os, the provider should try to pick up the default system pkcs11 module, which is in most of the cases p11-kit. This adds it as a default fallback option through `--with-default-pkcs11-module=yes`, which will ask p11-kit for this path through the pkg_config.
This also adds a implicit failure in case of no module was specified in any of the above means, which leads to dlopen call with NULL argument opening the …
> Add different ways for specifying PKCS#11 module to use

- src/provider.c
Previous PR forgot to free ctx on error condition.
> CID 361508: Resource Leak

- src/keymgmt.c
- src/provider.c
- src/provider.h
- src/store.c
- tests/openssl.cnf.in
- tests/test.sh
Add function to allow exporting EC public keys.
Add option to deny exporting public keys so processing stays on the token.
Fixes #69
> Improve public key export

- .reuse/dep5
- BUILD.md
- packaging/pkcs11-provider.spec
While getting familiar with this package, I prepared a spec file and build the packages in copr:
https://copr.fedorainfracloud.org/coprs/jjelen/pkcs11-provider/monitor/
From here, it should be easy to integrate the packit to automate the builds.
The tests now fail on s390x on signature verification test on all Fedora versions, but I was not able to investigate this further yet:
```
openssl dgst -sha256 -binary -out ${TMPPDIR}/sha256.bin ${SEEDFILE}
openssl pkeyutl -sign -inkey "${PRIURI}" -in ${TMPPDIR}/sha256.bin -out ${TMPPDIR}/sha256-sig.bin
openssl pkeyutl -verify -inkey "${PUBURI}" -pubin -in ${TMPPDIR}/sha256.bin -sigfile ${TMPPDIR}/sha256-sig.bin
000003FFB0772720:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:crypto/rsa/rsa_pk1.c:75: …
```
> Fedora package and requirements clarifications

- src/encoder.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- tests/openssl.cnf.in
- tests/test.sh
This required several changes
- Some fixes to signature code
- Add ability to return DER formatted algorithm-id to be included in CSR
- Add support for encoding SubjectPublicKeyInfo in DER format to be included in CSR
- Ability to fetch the corresponding public key when we need to export public attributes and are given a private key
- Other general fixes
Fixes #88
> Add support for generating CSRs via openssl req command

- src/store.c
- src/util.c
The non-underscored constants in `endian.h` only if the `__USE_MISC` is defined for some reason. This fixes the failing tests on s390x during the build in copr:
https://copr.fedorainfracloud.org/coprs/jjelen/pkcs11-provider/monitor/
Fixes #96
> Fix detection of endianness

- src/keymgmt.c
- src/signature.c
This is needed in some cases where openssl needs to check that a public key in a cert on file matches with the private key provided in a pkcs11 URI, like int he openssl ca command.
Depends on this PR: https://github.com/openssl/openssl/pull/19648
Manually tested wth the PR above on OpenSSL Master tree
Fixes #94
Fixes #99
> Fix openssl ca certificate releated issues

- src/keymgmt.c
Somhow I fat fingered and removed the return instruction from a conditional check. Kudos to Coverity for finding this stuff out.
> CID 376412: Fix lost error out

- .gitignore
- src/Makefile.am
- src/asymmetric_cipher.c
- src/digests.c
- src/exchange.c
- src/kdf.c
- src/provider.c
- src/provider.h
- src/signature.c
- tests/Makefile.am
- tests/tdigests.c
- tests/test-digests-softhsm.sh
- tests/test-digests-softokn.sh
- tests/test.sh
Add the digest provider functions.
Refactor code to use helpers from digest.c so all places use a single mapping function that will be easier to keep up to date.
Add tests.
> Add support to expose digest mechanisms through the provider

- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- packaging/pkcs11-provider.spec
- src/Makefile.am
- tests/openssl.cnf.in
It is a little bit silly to name a provider something-provider, and other openssl providers just use their name.so (for examnple tpm2.so), so let's do the same for the pkcs11 provider and install it propoerly under /libdir/ossl-modules/pkcs11.so as expected by openssl provider distribution standards.
Also add a dstribution check CI tests, that runs make distcheck and builds an rpm from the spec file
> Rename the module binary to just pkcs11.so

- tests/Makefile.am
- tests/openssl.cnf.in
- tests/setup-softhsm.sh
- tests/setup-softokn.sh
- tests/softhsm-proxy.sh
- tests/tbasic
- tests/teccsha2
- tests/test-wrapper
- tests/thkdf
- tests/toaepsha2
- tests/trsapss
The test now work when built in the source or some other directory and configured like ../pkcs11-provider/configure
Fixes: #109
Define "testblddir" and "TESTBLDDIR" to point to the build/test directory i.e. "@abs_top_builddir@/tests" and correct several places where original code made some assumptions that the source directory was the same as the build directory.
`tests/test-wrapper` was patched to allow a file path name to include "-" It would fail to run some of the tests because it would not find the command an options.
The export PINFILE="${BASEDIR}/${PINFILE}" work when basename was null as previously in code it was already defined as PINFILE="${PWD}/pinfile.txt"
Changes to be committed:
modified:   tests/Makefile.am
modified:   tests/openssl.cnf.in
modified:   tests/setup-softhsm.sh …
> Fix "tests" when built outside source directory

- src/asymmetric_cipher.c
- src/exchange.c
- src/kdf.c
- src/signature.c
OSSL_PARAM_get_utf8_string_ptr() returns pointer to the data of OSSL_PARAM data and does not copy or allocate memory.
Prefer its usage when it makes sense.
> Use OSSL_PARAM_get_utf8_string_ptr() when possible

- src/Makefile.am
- src/asymmetric_cipher.c
- src/encoder.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/objects.c
- src/provider.h
- src/session.c
- src/signature.c
- src/store.c
- src/util.c
This PR refactors how objects are stored.
In particular it merges the P11PROV_KEY structure into P11PROV_OBJ and adds support for representing both keys and certificates from a single object.
All code from keys.c and some from store.c is moved to objects.c
> Add basic support to load certificates from tokens

- src/provider.c
Otherwise the strncmp() matching against pksc11 URI fails.
> Remove space padding from slot and token info

- src/signature.c
Changes to data:
- DER_ECSHA2_SEQ_LEN was incorrectly 0x10 (should've been 0x0A)
- DER_SEQ_ECDSA_SHA3_* incorrectly contained the NULL tag
> Simplify and fix signature DER AlgorithmInfo

- src/signature.c
- tests/tbasic
A DigestInfo DER structure should be constructred and signed when signing a pre-calculated hash with known digest.
fixes #113
> Fix RSA signatures with pre-calculated hash

- src/objects.c
- src/signature.c
Minor formatting errors in debug messages caught by Coverity.
> Coverity fixes #10

- src/session.c
- src/util.c
This was initially shared as part of #126 but submitting this separately as it was was not related to the login issues.
* The unused struct member can be removed
* The `object-type=secret` had wrong length
* In `token_login()` delaying the session allocation simplifies the process and prevents log pollution in case the login is not needed.
> Minor fixups found during code review and experiments

- src/objects.c
- src/provider.h
- src/util.c
Allow the code to try not only to find an associated public key, but to also fallback further to try to find a certificate object and extract the public key attributes from that object.
Fixes #127
> Add fallback to cert to get public key attributes

- src/session.c
- tests/tbasic
Really require a login only if the calling code says a token is required. The calling code generally know when it is using a private key or performing other operation that generally requires logins.
> Defer requiring login to token

- src/asymmetric_cipher.c
- src/digests.c
- src/kdf.c
- src/keymgmt.c
- src/objects.c
- src/provider.c
- src/provider.h
- src/session.c
- src/signature.c
- src/store.c
This PR handles optimizing iteration and usage of slots.
We skip completely slots that are at fault (can't fetch information) or where the token is not present.
We also now check that the token can handle the operation we are trying to perform at the time we request a session. This helps selecting the correct token on some operation when multiple tokens are available, and in general fails earlier if the token does not support the requested mechanism.
> Skip slots that are not usable and check mechanism before selecting slot

- src/Makefile.am
- src/asymmetric_cipher.c
- src/debug.c
- src/digests.c
- src/exchange.c
- src/interface.c
- src/kdf.c
- src/keymgmt.c
- src/objects.c
- src/provider.c
- src/provider.h
- src/session.c
- src/signature.c
- src/util.c
This allows us a few things:
- Support multiple PKCS#11 version drivers
- Add automatic debugging/tracing and error reporting for each PKCS#11 function called
- Gain information on whether the token is modern enough to support forking processes
Additionally this allowed to remove a lot of cruft and some odd calls to p11prov_ctx_status() making some code a lot more readable.
> Wrap PKCS#11 interface calls

- src/objects.c
- src/session.c
Search all objects first and resolve them only after the FindObjectsInit / FindObjects / FindObjectsFinal loop is complete. This handles some tokens that may have issues handling more than one kind of operation per session, even though legal per spec.
Fixes #148
> Use closed loop for FindObjectsInit/Final

- configure.ac
This patch allows building the provider against custom openssl build located aside. It's useful for debug purposes and is relevant for old systems having openssl 1.1.1 on board
> Allow pass custom OpenSSL dir

- src/encoder.c
- src/encoder.h
- src/keymgmt.c
- src/objects.c
- src/objects.h
- src/provider.c
- src/store.c
- tests/helpers.sh
- tests/tbasic
- Streamlines rsa public key printing
- Allow to print public key data from private keys
- Add EC public key printing.
- Match printing style from OpenSSL's existing text encoders
> Small enhancements to encoder.c

- src/asymmetric_cipher.c
- src/digests.c
- src/exchange.c
- src/interface.c
- src/interface.h
- src/kdf.c
- src/keymgmt.c
- src/objects.c
- src/objects.h
- src/provider.c
- src/provider.h
- src/session.c
- src/session.h
- src/signature.c
- src/store.c
- src/util.c
- src/util.h
This code currently uses the login_session session as a stable, long term, open session.
Using any other session would require keeping another session open for as long as any key is cached.
Resolves: #55
> Caching of keys in session objects and refactoring of session management

- src/digests.c
- src/objects.c
- src/session.c
Coverity this time found a pretty important locking issues among the usual crop of minor printf format in debug statements.
> Some interesting coverity discoveries

- src/exchange.c
- src/kdf.c
- src/objects.c
- src/util.c
- src/util.h
This allows for writing much shorter functions with a lot less auxiliary variables needed.
It also avoids many manual coding errors by providing more utility functions.
> Streamlinbe fetch_attrs interface

- .github/workflows/build.yml
- .gitignore
- src/interface.c
- src/keymgmt.c
- src/objects.c
- src/objects.h
- tests/Makefile.am
- tests/treadkeys.c
The openssl excersises different code paths when accessing OSSL_PARAMS of a
provided EVP_PKEY structures. While going with EVP_PKEY_todata() works as
expected, using EVP_PKEY_get_utf8_string_param() goes through different code
path to retrive the parameters and in current version fails.
> Allow retrieving group name for EC keys

- src/session.c
In which case return early and do not even try to login and go through operations that will fail.
> Detect if token is write protected

- src/objects.c
- src/objects.h
Use vendor defined attributes to store additional parameters pre-formatted to OpenSSL liking, this way we can remove a lot of ASN1 reparsing done in multiple places on demand.
> Optimize EC_KEY data parsing and storage

- src/session.c
In PR #156 an attempt to fix some minor locking issues resulted in a much worse potential deadlock within the code that attempts to create a login session.
The code roughly did the following:
token_login {
/* A section */
lock -> pool
lock -> session
unlock -> pool
/* issue  */
/* B section */
lock->pool
unlock->pool
return
}
After section A, we hold the session lock, but do not hold the pool lock, that means another thread could be calling token_login() before we enter section B, and take the pool lock.
Then attempt to take the session lock and be stuck waiting. At the same time the original thread will be stuck trying to get the pool lock in section B, and not releaseing the session lock. This is a classic deadlock situation and both threads will wait forever.
The basic solution is to …
> Session locking fixes

- src/session.c
Just one more coverity fix after #162 was pushed.
The good news is that all the items coverity found about locking where intentional choices (like returning a locked object from a function which coverity flags as "forgot to unlock").
Only a printf format mistake remains.
> CID 433656: Invalid type in argument to printf

- src/provider.c
- src/session.c
Adds support for CKF_PROTECTED_AUTHENTICATION_PATH and prevents repeating authantication with the same failed pin.
Fixes #160
> Improve authentication to tokens

- src/keymgmt.c
- src/session.c
- src/session.h
This PR aims to address #161
I do not say fix because there is no requirement for a token to call callbacks.
In fact neither softokn nor softhsm call them during key generation so we can't regularly test this code.
However I manually tested that everything works well from pkcs11-provider up my hardcoding a few calls to token_session_callback() and running openssl genpkey and have verified that dots are printed by openssl (we return only zeros in the params and they correspond to the '.' char).
Resolves #161
> Key generation callbacks

- src/session.c
- src/util.c
- src/util.h
Asprintf is convenient but causes mixing of OPENSSL and standard memory management in the code base which can quickly lead to bad problems, undetected until an application changes the openssl allocators.
> Eliminate use of asprintf

- tests/tcerts
For certs, at some point the master tree has changed the way Subjects are printed (remving spaces around the equal signs that separates attribute names from values in DNs).
Fix tests to cope with both older and newer formatting.
> Fix test as OpenSSL change output formatting

- .github/workflows/build.yml
- configure.ac
- src/provider.h
- src/session.c
- src/tls.c
- src/util.c
- tests/Makefile.am
- tests/openssl.cnf.in
- tests/setup-softhsm.sh
- tests/setup-softokn.sh
- tests/ttls.c
macOS requires `_XOPEN_SOURCE=600` for snprintf(3) and vsnprintf(3). The previous value of `_XOPEN_SOURCE=500` hides the declaration.
`src/session.c` uses `ssize_t` which is in `sys/types.h` on macOS.
Also fix libsoftokn3 detection on macOS in configure.ac:
macOS uses `.dylib` as extension for shared libraries, but `.so` for loadable modules. NSS seems to treat libsoftokn3 as shared library, so it uses `.dylib`.
Autoconf has `$SHARED_EXT` for the platform-specific library suffix, so use that. Add a comment above `p11-kit-client.so` indicating that this is correct so we don't change it accidentally in the future.
See: #179
> macOS build fixes

- src/exchange.c
- src/kdf.c
- src/objects.c
- src/util.c
- src/util.h
REduce the size and reuse the CK_ATTRIBUTE structure within fetch_attrs to further simplify copying data between attribute storages when needed.
Also fix some checks in the derive key functions that I found wrong while refactoring.
Fixes #163
> Simplify utulity to fetch attributes

- src/provider.c
- src/provider.h
- src/store.c
This is to account for the case where HSMs may require login even for public objects. They will return no objects at all unless there is a login session.
If a user is sure their token always allow public objects to be retrieved w/o PIN there is a tunable that can be set to avoid the fallback annoyance when the pkcs11 uri is imply not matching a public key correctly.
Fixes #196
> Retry store_fetch with login if nothing found

- src/debug.c
This fixes crash when debug log file is not specified in the `PKCS11_PROVIDER_DEBUG` environment variable (e.g. `PKCS11_PROVIDER_DEBUG=level:99`). The bug has been introduced in commit b39e45e9.
> Fix broken debug output to stderr

- src/session.c
- src/session.h
- src/signature.c
I decided the simplest hing is to return early if the token does not support RSA PSS rather then trying to emulate it via raw RSA, because usually the pkcs11 driver emulates PSS on its own if raw RSA is available at all.
If it is not it is generally because the token is supporting only PKCS in Hardware and can't do PSS at all.
Fixes #194
> Error early if RSA PSS is not supported

- src/interface.c
- src/interface.gen.c
- src/interface.h
- src/interface.pre
- src/keymgmt.c
- src/provider.c
- src/provider.h
- src/store.c
This patchset delays pkcs11 modules initialization until an application actually causes openssl to try to use pkcs11-provider for some operation.
This requires to make keymgmt static, because keymgm and store interfaces can be called directly by openssl before any other fnction causes module initialization.
All direct entrypoints now must call pkcs11_ctx_status() which causes module intialization and returns an error if it fails.
Fixes #187
> Delay pkcs11 module loading and initialization

- src/provider.c
- src/provider.h
- tests/Makefile.am
- tests/openssl.cnf.in
- tests/tdigest
This deals with the delayed initialization issue and the tdigests test, by adding an option to bring back early initialization.
I tried to deal with dynamic loading of digests by providing a static set of digests always but asking openssl not to cache the provided digests in p11prov_query_operation() by setting no_cache = 1, but this seemed not only to cache the digest alogotihms, insuring the dynamically loaded once would be completely ignored, but also result in these digest algorithms being preferred to the default module digests.
The exact opposite of what we wanted to have.
Fixes #211
> Add early load behavior configuration and test it

- src/provider.c
- src/provider.h
- src/session.c
- src/store.c
This allows to suppress errors stored on the stack in places where we can retry operations, so we reduce the amount of noise reported to users in case of failure.
Fixes #212
> Add support for setting/removing error stack marks

- src/provider.c
This error is not going to cause issues in practice as the structure currently only contains a string anyway, so the address of the structure does in fact correspond to the address of the string we want to print. But in future may return garbage if the structure is changed.
> CID 451133: Fix errors using config option names

- src/signature.c
- src/util.c
This allows things like generating certificates when default_md is not set to work out of the box.
Fixes #223
> Set default digest for digest_sign/verify functions

- src/provider.c
- src/slot.c
- tests/Makefile.am
- tests/openssl.cnf.in
- tests/setup-softhsm.sh
This allows to avoid some issues with bad modules that link into openssl or have atexit() handlers that interfere with graceful shutdown.'
Tested against the YubiHSM pkcs#11 driver which hangs and another vendor cloud HSM driver which segfaults.
> Add a quirk to prevent calling the module on exit

- src/keymgmt.c
- tests/tedwards
This is needed to inform OpenSSL that EDDSA must not use a digest, and also allow openssl to inquire what the default digest is, if any.
> Support OSSL_PKEY_PARAM_DEFAULT/MANDATORY_DIGEST

- src/keymgmt.c
OpenSSL often asks for all possible things via selection, even when it knows it just has a public key on hand.
Allow export to go through if the key type matches, even when openssl asks for things it can't possibly get anyway.
Fixes #198
> Fix public key exporting

- src/signature.c
- src/util.c
- tests/ttls
Looks like SoftHSM sometimes returns an empty CKA_ALLOWED_MECHANISMS attributes, which clearly makes no sense.
For right now we work around this, if no mechanisms are really allowed a following operation will simply fail anyway.
Fixes #217
> Fix SoftHSM issues wth PSS keys

- src/encoder.c
- src/objects.c
- src/provider.c
- src/provider.h
- src/session.c
- src/slot.c
- src/slot.h
- src/util.c
- src/util.h
- tests/Makefile.am
- tests/helpers.sh
- tests/tbasic
- tests/tecc
- tests/tedwards
- tests/tpubkey
- tests/turi
Overhaul how URI are parsed.
Add missing attributes specified in [RFC 7512](https://www.rfc-editor.org/rfc/rfc7512)
Print URIs instead of ID/Label in text encoders
> Improve URI management

- .github/workflows/style.yml
- src/Makefile.am
- src/interface.c
- src/interface.gen.c
- src/interface.h
- src/interface.pre
- src/provider.c
- src/provider.h
- src/random.c
- src/random.h
- tests/Makefile.am
- tests/openssl.cnf.in
- tests/trand
> Implement support to expose PKCS#11 Random as openssl rand provider

- src/provider.c
- src/provider.h
- src/util.c
- src/util.h
Quirk to completely disable requesting CKA_ALLOWED_MECHANISM attribute.
This is to aid investigation of #234
> Add quirk to control CKA_ALLOWED_MECHANISMS

- .github/workflows/distcheck.yml
- Makefile.am
- packaging/pkcs11-provider.spec
Fixes to spec file to include the right release, source URL, man page and docs.
These errors were discovered by fedora-review
https://bugzilla.redhat.com/show_bug.cgi?id=2211754
> Fixes to spec file to include the right release, source URL, man page, and docs.

- .github/workflows/build.yml
- .github/workflows/coverity-scan.yml
- .github/workflows/distcheck.yml
- .github/workflows/reuse.yml
- .github/workflows/scan-build.yml
- .github/workflows/shellcheck.yml
- .github/workflows/style.yml
- tests/helpers.sh
- tests/setup-softhsm.sh
- tests/setup-softokn.sh
- tests/softhsm-proxy.sh
- tests/tbasic
- tests/tcerts
- tests/tdemoca
- tests/tdigest
- tests/tecc
- tests/tecdh
- tests/tedwards
- tests/test-wrapper
- tests/thkdf
- tests/toaepsha2
- tests/tpubkey
- tests/trand
- tests/trsapss
- tests/ttls
- tests/turi
Follow-up to #254 where the shell did not do what it was supposed to be doing, I decided to take shellcheck into action and squash the warnings to keep the tests "clean". On the way I also reformatted they github yml files as the editor was going craze every time I had to touch them.
> Run Shellcheck as part of CI and squash the shellcheck and yamlint warnings

- configure.ac
Currently value for CRYPTO_LIBS  has a bogus value.
PKG_CHECK_MODULES automatically creates _LIBS flag ([See](https://developer-old.gnome.org/anjuta-build-tutorial/stable/library-autotools.html.en) ). This was missing for [CRYPTO].
Due do this, rpmlint -i test on the [rpm](https://download.copr.fedorainfracloud.org/results/saprasad/pkcs11-provider/fedora-rawhide-x86_64/06125202-pkcs11-provider/pkcs11-provider-0.1-1.fc39.x86_64.rpm) had 106 warning like:
pkcs11-provider.x86_64: W: undefined-non-weak-symbol /usr/lib64/ossl-modules/pkcs11.so ASN1_INTEGER_it»·(/usr/lib64/ossl-modules/pkcs11.so)
And libcrypto.so was missing in Requires
Requires
pkcs11-provider (rpmlib, GLIBC filtered):
libc.so.6()(64bit)
rtld(GNU_HASH)
This PR fixes the above issues.
[root@vm-10-0-187-0 packaging]# ldd …
> Set the value for CRYPTO_LIBS flag correctly

- packaging/pkcs11-provider.spec
Enable gpg signature verification in spec file with option gpgcheck
to enable this in rpmbuilds, use
rpmbuild -ba --with=gpgcheck pkcs11-provider.spec
(It is disabled by default in  upstream CI)
Test logs:
[root@vm-10-0-184-239 packaging]# rpmbuild -ba --with=gpgcheck pkcs11-provider.spec 
setting SOURCE_DATE_EPOCH=1688947200
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.BRyc8l
+ umask 022
+ cd /root/rpmbuild/BUILD
+ /usr/lib/rpm/redhat/gpgverify --keyring=/root/rpmbuild/SOURCES/simo_redhat.asc --signature=/root/rpmbuild/SOURCES/pkcs11-provider-0.2.tar.xz.asc --data=/root/rpmbuild/SOURCES/pkcs11-provider-0.2.tar.xz
gpgv: Signature made Fri Jul  7 06:11:53 2023 EDT
gpgv:                using RSA key 7C7BD146943B206BB645B64594EAD67E004B65AB
gpgv:                issuer "simo@redhat.com" …
> Enable gpg signature verification in spec file

- src/session.c
- src/slot.c
- src/slot.h
Encountered an issue with tokens that don't require login while using this provider with https://github.com/tpm2-software/tpm2-pkcs11 where sign operations would not complete properly and always produced an error due to login error.
This is a proposal to just skip the token login if the flag CKF_LOGIN_REQUIRED is not present.
I'm not sure if there are any side effects to this but it at least solved my issue.
> Skip login if token does not require login

- src/encoder.c
- src/interface.c
- src/keymgmt.c
- src/objects.c
- src/objects.h
- src/slot.c
- src/slot.h
- src/store.c
- tests/Makefile.am
- tests/tbasic
- tests/tcmpkeys.c
- tests/tgenkey.c
This are various fixes to small things I had in my tree and to recent issues reported in #265 and #266 
Note that I changed how export work, including an attempt to re-enable direct export from store and then again disable it.
> Change how key export works, and add key import functionality as well as key match

- src/session.c
- src/store.c
Although we want to ensure a login session is available for certain operations, we also do not want to unnecessarily fail them when mutliple operations are running concurrently.
As login status is token global, all we need to ensure is that a login session exist. This can be reasonably easily determined by session status as well.
So where we do not actually need to use the login_session directly we can simply check the status and return positively.
The only place that really wants to use a login_session directly is the caching layer which is tolerant to failure already.
> Smarten up handling of login session

- src/keymgmt.c
- src/objects.c
- src/objects.h
- tests/Makefile.am
- tests/tcms
This PR implements `set_params` method for EC keys that allows assigning `OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY` parameter. This parameter is required for `EVP_PKEY_set1_encoded_public_key` to function properly. This function is in turn used by `CMS_decrypt_set1_pkey_and_peer` so without this decrypting a CMS does not work at all.
This PR also adds a test to check CMS encrypt/decrypt using an EC key. Since decrypting a CMS uses `CKM_ECDH1_DERIVE` mechanism with shared data the test is being run on nss-softokn only. Although SoftHSM2 also supports ECDH1 derivation mechanism it currently (https://github.com/opendnssec/SoftHSMv2/pull/599) only does when no shared data is specified.
> Allow setting OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY for EC keys

- src/interface.c
- src/interface.h
- src/provider.c
This prevent multiple threads from stomping on each other and reinit the module multiple times.
Fixes #281
> Reinit module only once after fork

- src/objects.c
- src/session.c
Some code really need to obatin a session from a login. Some other code just need to attempt but can fail. If a login session is in use cycle again until we have a login session for sure if the calling code really requires a logged in token.
Fixes #287
> Plug a small race in token login operations

- src/keymgmt.c
- src/provider.h
- tests/tgenkey.c
This allows an application finer control on what usage will be allowed for the key.
Fixes #285
> Implement special parameter to define Key Usage

- src/keymgmt.c
- Fix EC private key generation template size
- Fix p11prov_common_gen_init debug log entry
> Fix key generation template size and debug log message

- configure.ac
From the man-page on the `AC_CHECK_FILE` macro, we can read that:
```
You might also need to check for the existence of files. Before using these macros, ask yourself whether a runtime test might not be a better solution. Be aware that, like most Autoconf macros, they test a feature of the host machine, and therefore, they die when cross-compiling.
```
Therefore, move to using a simple shell if/else as the replacement.
> Fix: enable cross compilation by removing the AC_CHECK_FILE macro

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- tests/tbasic
After Debian pulled fixed NSS version, we started getting the failure where the basic test expected public key data to be printed when we selected private key. This was probably the case in some openssl versions, but given that the test reads explicitly private key uri, I think checking for the private key information makes more sense.
> tests: Fix expected output and fix Debian package name

- src/asymmetric_cipher.c
- src/interface.c
- src/interface.h
- src/util.h
Fixes for CVE-2023-6258 (Marvin)
> Side-channel proofing PKCS#1 1.5 paths (CVE-2023-6258)

- src/provider.c
- src/session.c
These are locking related.
There wasn't anything really wrong in the code, because of external guarantees, and some actions were intentional.
However Coverity rightfully complains as from a strict pov the code was not always properly following a consistent use of locking.
This may call for followup PRs to make Coverity happy if this first round is not sufficient.
> Minor coverity fixes

- src/session.c
@Jakuje these were introduced with your PR and caught by Coverity.
They seem pretty obvious fixes, bug given our CI is half broken now (all tests pass locally on my system using gnutls 3.8.1) just asking a token review before pushing through.
> Apply coverity Fixes

- src/objects.c
- src/util.c
- src/util.h
This allows us to retain better information about the object and critically things like a PIN passed in the URI to be able to login to the token after a fork when the PIN is not specified in the token configuration.
Fixes #313
> Use a cached version of the URI to refresh objects

- tests/ttls
I ran into some flakeyness when running the TLS tests with a HSM.
I changed the test to use expect such that the timing for sending stuff to the server and the client process depends on the program output.
> tests: tls test without sleep

- .github/workflows/shellcheck.yml
- .gitignore
- docs/provider-pkcs11.7
- docs/provider-pkcs11.7.md
- src/digests.c
- src/provider.c
- src/provider.h
- src/signature.c
- tests/Makefile.am
- tests/tdigest_dupctx.c
- tests/top_state
Configuration property to indicate whether the PKCS11 provider supports getting/setting the operation state. If it is not supported, no attempts will be made to duplicate the context.
I already mentioned it in the discussion (https://github.com/latchset/pkcs11-provider/discussions/320) that the current approach leaves traces in the SSL error stack.
Please let me know what you think of this change.
(Tests will follow)
> Quirk: no-operation-state

- BUILD.md
I am not very familiar with GNU Autotools, so it wasn't clear to me that I need to pass a path to --with-openssl. Running `./configure --with-openssl` will result in the following error:
~~~
libtool:   error: cannot determine absolute directory name of 'yes'
~~~
Because the missing path is just replaced with 'yes'.
Clarify that --with-openssl must be passed a path, e.g., `--with-openssl=/usr/lib64`.
> Add --with-openssl info to BUILD.md

- README.md
Replace with note about wher to file Security issues
> Remove obsolete pointer to docs in the wiki

- docs/provider-pkcs11.7.md
- src/provider.c
- src/provider.h
- src/session.c
- tests/top_state
Fixes https://github.com/latchset/pkcs11-provider/issues/342
More details in the issue description. 
I'm not really a C developer so any suggestions for improvements will be highly appreciated
> Added an option to set NULL callbacks for C_OpenSession

- .github/workflows/integration.yml
This is the first sketch of integration CI. For now it only runs libssh upstream tests relevant for pkcs11 provider. It only work on fedora and takes about 2 minutes to complete the job. The idea is to add jobs for other provider consumers. It requires additional polishing (e.g. ctest passes even if it runs no tests).
> WIP: Run CI with integration test for libssh

- src/objects.c
This is an optimization to avoid having a copy of the EC public key on HSM: some vendor implementations add CKA_EC_POINT to CKK_EC/CKO_PRIVATE_KEY to facilitate `EVP_PKEY_eq()`-type comparisons—skip round-tripping to the HSM to find_associated_obj.
This optimization is in OpenSC/libp11 see: : https://github.com/OpenSC/libp11/commit/281ccb3d60e77366bd6ece4b8a18d5ef28cb4f45
For both PR#346 PR#347 I found a discussion on libp11 about the round-tripping issue: https://github.com/OpenSC/libp11/issues/209
> EC keys: implement vendor optimization when private key contains CKA_EC_POINT

- .github/workflows/address-sanitizer.yml
Debian is getting ready for 2038 (https://lwn.net/Articles/938149/). Apparently they have converted the libssl package. It is now necessary to install the *t64 version of the debug symbols.
> GH workflow install libssl3t64-dgbsym on debian

- .github/workflows/integration.yml
- tests/integration/bind.sh
- tests/integration/httpd.sh
- tests/integration/libssh.sh
This PR adds two new tests (for httpd and bind) and re-factors previously added test for libssh. Tests are intended to run in CI (github actions) but they can be executed on any Fedora (39 and newer) as follows (`GIT_URL`  defaults to this repository and `GIT_REF` to the main branch):
```
```
Testing requires bash -e option. Non-zero exit code means failure. Provider debug logs are always printed out at the end (regardless of the result). All three tests uses softhsm token (bind test does so via p11-kit server proxy). Please notice that until Fedora 40 is released both httpd and bind test need to use a specific docker image.
> Integration tests (libssh, httpd, bind)

- .gitignore
- src/encoder.c
- src/slot.c
- tests/Makefile.am
- tests/tfork_deadlock.c
- tests/tforking
The reason to acquire a write lock is that there is a corner case where
the forking application is going to actually create additional threads
in an atfork() handler that runs before ours instead of doing something
more sensible like an immediate exec().
If such an application were to create threads then there is a chance
one of those threads could cause a call into pkcs11-provider that would
end up acquiring a read lock, which we will destroy as part of the post
fork atfork() handler.
Note that pthread creation or even pthread lock initialization functions
are not considered async-sginal-safe fucntions, so this is all a shot in
the dark anyway ...
Given this premise, falling back to a read lock, which will prevent
modification of the slots is sufficient in most cases.
Although there is a …
> Fallback to a read lock on fork preparation

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/coverity-scan.yml
PR to change Coverity Scan to run on demand (by setting the covscan label) instead of running it after merge to main.
This way we can run the scan when the PR is still open and catch issues before merging.
N/A
> Try to run Coverity Scan on demand

- .gitignore
- .reuse/dep5
- tools/README.md
- tools/openssl-tools.cnf
- tools/tests/test_softoken.py
- tools/uri2pem.py
Add a cli tool to create PEM files in PKCS#11 PROVIDER URI format
[Updated] Usage:
usage: uri2pem.py [-h] [--bypass] [--verify] [--out OUTPUT_FILE] keyuri
positional arguments:
keyuri             the PKCS#11 key URI to encode
options:
-h, --help         show this help message and exit
--bypass           skip basic URI checks
--verify           verify PEM file with OpenSSL; requires --out to be specified
--out OUTPUT_FILE  output to PEM file, otherwise to stdout
Example run:
```
OPENSSL_CONF=../../softoken/openssl.cnf python uri2pem.py  \
--verify --out something.pem \
'pkcs11:model=NSS%203;manufacturer=Mozilla...type=private'
===== OpenSSL pkey output =====
-----BEGIN RSA PUBLIC KEY-----
MIIBigKCAYEA3BE+a2ysvJMZuccg3QU51dabXNF/XAo5/iUP0UGHLtAYolLlkz2j …
```
> Add uri2pem.py tool to create pkcs11-provider PEM key files

- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- .reuse/dep5
- m4/ax_valgrind_check.m4
- tests/setup-softhsm.sh
- tests/tdemoca
- tests/tecxc
The Debian is unstable so it is moving quite fast with the OpenSSL versions. Fedora will update from OpenSSL 3.1 to 3.2 in coming month so we will not be able to check the changes keep working with older OpenSSL versions, which is our interest for RHEL9.
> ci: Run tests also against CentOS 9 (OpenSSL 3.0)

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- .github/workflows/reuse.yml
- .github/workflows/scan-build.yml
- .github/workflows/shellcheck.yml
- .github/workflows/style.yml
Include change to avoid warnings dumped by old versions of Github actions
> Avoid warnings related to Node20 Github actions

- src/provider.c
OpenSSL calls `p11prov_query_operation()` to query which operations the provider supports. With the `no_cache` function argument, the provider can tell OpenSSL if it is OK to cache the query results or not.
As soon as the PKCS#11 provider has fully initialized, it is OK to cache the operations, since they won't change during the lifetime of the provider. However, when the provider has not yet fully initialized, only the `KEYMGMT`, `DECODER`, and `STORE` operations are fully set up (they are static), but the other operations have not been set up, and may change when the operations are eventually initialized. Thus, these operations can not be cached as long as the provider status is still in 'uninitialized' state.
Operations that the provider does not support at all can always be cached. …
> Do not cache operations when provider status is uninitialized

- .github/workflows/coverity-scan.yml
Otherwise Github thinks both are required to pass a PR, but actually only the PR one is as the scheduled scan only runs on a schedule.
> Change names of the two covscan jobs

- tests/setup-softhsm.sh
- tests/setup-softokn.sh
As described in #360, correct format for pin-value option in URI is for it to be after '?', rather than as an additional URI path. This change sets the values appropriately in tests to identify possible parser issues
Fixes #360
> Set correct pin-value format in tests

- .github/workflows/build.yml
macOS 12 was released in October 21, and since then 13 has been out in October 22, and 14 in September 23. Switch to a more recent Mac operating system since that's likely what users will be running.
See [\[1\]][1] for GitHub's list of available shared runners. From the macos-12 label to the macos-14 label, the number of CPU cores stays the same (3), but the CPU architecture switches from x86_64 to arm64. All other parameters stay the same except for RAM, which changes from 14 GB to 7 GB. Since pkcs11-provider is not a memory intensive project, this likely has negligible impact on us. The new CPU architecture can be helpful to identify hardware-specific issues, so is probably a net positive. The M series chips are also typically much faster than the older Intel counterparts.
[1]: …
> ci: Switch to macOS 14 on M series chips

- src/digests.c
- src/interface.gen.c
- src/interface.h
- src/interface.pre
- src/pk11_uri.gen.c
- src/provider.c
- src/provider.h
- src/signature.c
Introduce a generic mechanism to block calls to a token.
Use this mechanism to reimplement the no_operation_state quirk.
Fixes #327
> Use a genereic mechanism to block calls to tokens

- src/keymgmt.c
- src/objects.c
- src/objects.h
- tests/Makefile.am
- tests/tbasic
- tests/tcmpkeys.c
- tests/tedwards
- tests/tgenkey.c
Implements tests requested in #272
Fixes #272
> Add more generic EdDSA tests

- src/decoder.c
- src/encoder.c
- src/encoder.h
- src/keymgmt.c
- src/objects.c
- src/provider.c
- tests/setup-softhsm.sh
- tests/tbasic
- tests/tedwards
Fixes #272.
Now, it fails though. If I read it right, the OpenSSL returns `OSSL_STORE_INFO_PARAMS` type from the STORE API when I read the public PEM file exported from the provider, while I do not see anything missing in there so I will just drop it here and hope to get back to investigate the issue later.
> implement more tests with EdDSA keys (export and comparison)

- src/meson.build
OpenSSL's `libcrypto.pc` file does expose the correct path for providers in the `modulesdir` pkg-config variable (queryable using `pkg-config --variable=modulesdir libcrypto`), and we do obtain that path in `./meson.build`.
However, that variable is unused at the moment, and instead `src/meson.build` "guesses" that path as `$libdir/ossl-modules`, which may not actually be correct.
> build: Install provider in correct path

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- Makefile
- tests/meson.build
- tests/test-wrapper
The change to the meson build system regressed some minor things that I am attempting to fix here:
- Output also individual log files
Meson defaults to a ginormous log file with the output of all tests mashed together, this works but makes looking at specific test failures harder.
- Turn the custom targets that werre setting up tests into "tests", this allows us to run them only during the tests phase and not during the compile phase, which is unwanted
- Add dependencies from tests to test executables so they are rebuilt if missing
- Change make targets so we only build pkcs11.so and not all of the tests as well, this prevents coverity from flagging stuff in the test suite among other things
- Do not run tests in parallel, there are some unstated dependencies between tests so they will …
> Address various issues with meson builds

- .github/workflows/coverity-scan.yml
The Coverity Scan job that runs on PRs is supposed to pull the PR code when running in the pull_request_target case, but it is sourcing the incorrect ref.
Also The Coverity Scan is blocking, but we do not want to run it when there are no code changes, so add a new no-covscan label that makes the test pass w/o running one of the 4 covscan jobs/day we are allowed.
>  fixing Covscan PR target

- src/session.c
Since commit f1e85afeb0fe ("Session locking fixes") the session count variables are int. This is wrong since max_sessions is initialized by the token ulMaxSessionCount member so it of type CK_ULONG. Interpreting it as int is wrong since all values >= BIT(31) are interpreted as negative value.
Fix this by converting all session counting vars back to CK_ULONG.
> Fix session count types

- src/keymgmt.c
Let *that* cycle back into the provider and call C_GenerateRandom() if that's how the properties end up wiring things.
Fixes #280
After some consideration I think using the openssl RAND functions is just fine here.
First of all it is not a security sensitive thing, and secondarily those functions will still cycle back to use the C_GenerateRandom function if we probed that the token does have a random generator and properties force it.
The existing generation test should eb sufficient to cover this change, and no documentation needs to be updated.
> Use OpenSSL random functions

- .github/workflows/coverity-scan.yml
- .github/workflows/integration.yml
Some CI maintenance
- Disabled failing Bind integration tests
- Better covscan related label/status management
Only two labels exist:
- covscan
This label triggers an actual covscan run, do not abuse we have only 4 scans per day total
- covscan-ok
Once one of the admins receives the report set this label if passed
1. On setting covscan label a coverity scan is triggered and results are sent to an admin, the covscan label is removed to prevent unwanted re-runs and to avoid confusion on the status of the PR
2. On setting the covscan-ok label the covertiy test passes (test is green)
3. On pushing new commits if no labels are present:
- if no files in src/* are touched in the whole PR covscan will be deemed no neccessary (test is green)
- if any file in src/* is changed in any commit then …
> CI Maintenance

- src/asymmetric_cipher.c
- src/util.h
On x86 CK_ULONG and size_t have different sizes, ensure we use compatible types on our helper functions.
> Fix types for old 32 bit systems

- src/objects.c
CKA_ALWAYS_AUTHENTICATE is an attribute that exists only on private keys, do not attempt to fetch it when looking up public keys.
Fixes #405
> Fetch CKA_ALWAYS_AUTHENTICATE only for priv keys

- BUILD.md
- HOWTO.md
- README.md
Currently, there are multiple documentation files that are not connected in any way.  This PR adds a brief project description (previously split into two places), licence badge and links to all the other documentation files (BUILD.md and HOWTO.md).  Small re-formatting was also applied to BUILD.md and HOWTO.md without removing existing or adding any new content. 
I considered adding more examples to HOWTO about key management. But once you configure openssl to use the provider (covered in HOWTO.md) the rest is really more about other tools (e.g. p11-kit) than the provider. 
I also did not cover tests but we can do that later if needed.
Resolves #301.
Not applicable
> Small re-organization of documentation files

- src/keymgmt.c
Coverity seem to have updated its rules and is now more concerned about integer overflows than before. This place has no change of overflowing, but lets play ball and silence it with a check.
CID 500198: Integer handling issues (INTEGER_OVERFLOW)
- ~[ ] Test suite updated with functionality tests~
- ~[ ] Test suite updated with negative tests~
- ~[ ] Any issues marked for closing are addressed~
- ~[ ] This feature/change has adequate documentation added~
- ~[x] Commits have short titles and sensible commit messages~
> Fix CID 500198: Integer handling issues

- tests/integration/libssh.sh
Minor fixes to the libssh integration test
> Libssh test fix

- src/objects.c
I'm getting a segmentation fault on this line because pool->objects can be NULL. I suspect this > should be >=, though I'm not quite sure.
> Off-by-one error in pool consistency check

- src/exchange.c
- src/objects.c
- src/objects.h
- tests/meson.build
Changes the format of the point passed into ECDH Params
Enables Kryoptic ECDH test, which now passes.
Fixes #416 
- ~[ ] This feature/change has adequate documentation added~
> Set the raw point for ECDH public data params

- tests/setup-kryoptic.sh
pkcs11-tool is well capable of initializing a token, so just use it for everything and drop use of p11tool which is quirkier.
- ~[ ] Code modified for feature~
- ~[ ] Test suite updated with negative tests~
- ~[ ] Any issues marked for closing are addressed~
- ~[ ] This feature/change has adequate documentation added~
- ~[ ] Coverity Scan has run if needed (code PR) and no new defects were found~
> Use a single tool for setting up the token

- src/keymgmt.c
- src/objects.c
We already have the value and a function to compute it from EC_POINT if needed, just return it when requested. It is sometimes used by openssl to get the public point for ECDH.
> Return OSSL_PKEY_PARAM_ENCODED_PUBLIC_KEY

- tests/meson.build
On macOS, the variable for library preloading is DYLD_INSERT_LIBRARIES, not LD_PRELOAD. Adjust the CHECKER env variable to use that on macOS machines.
Change fake_dlclose to a library rather than a shared module. This doesn't make a difference on Linux, but on macOS, dyld(1) refuses to insert a shared module into a processes address space using DYLD_INSERT_LIBRARIES, but allows a library in the same place.
> tests: Fix ASAN build on macOS

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- .github/workflows/kryoptic.yml
- .github/workflows/scan-build.yml
- tests/setup-kryoptic.sh
- tests/setup-softhsm.sh
- tests/setup-softokn.sh
- tests/softhsm-proxy.sh
- tests/ttls
The TLS tests now tests just the default parameters with RSA key. This PR extends it to test also TLS 1.2, ECDSA keys and specific ciphersuites.
> Extend the ttls test to be able to test different configurations

- tests/meson.build
- tests/setup-kryoptic.sh
- tests/trsapssam
This enabled ed25519 tests with kryoptic (and few more forgotten tests).
This depends on latchset/kryoptic#80. Tested locally with this branch.
> Enable Ed25519 tests (and other forgotten ones) for kryoptic

- src/keymgmt.c
This commit adds CKA_DERIVE flag in server's private key template which gets checked by optee subsystem to derive shared secret. Tested TLS1.2 with the change.
Without this flag enabled, tls connection fails while deriving shared secret.
This change is in common code, please let me know where I can change instead of changing common code.
> Add CKA_DERIVE flag in server's private key template

- tests/tpubkey
This condition was introduced at the time when we were running the softhsm under p11-kit proxy, which caused some issues to mac.
We no longer do this so there is no need to skip this test either.
> tests: No longer skip tests reading EC keys from cert

- tests/setup-kryoptic.sh
- tests/tedwards
- tests/tgenkey.c
The `pkcs11-tool` does not support generating these keys so we just test the internal key generation and processing with tgenkey.
> Add basic Ed448 tests

- src/objects.c
- tests/meson.build
- tests/tlssetkey.c
- tests/ttls
- tests/util.c
- tests/util.h
This behavior is needed to pass some openssl consistency checks with tokens that store the public key only in a cert object.
Fixes #430 
> Allow fallback to pulling cert when checking private/public key consistency

- src/keymgmt.c
This commit updates EC_PRIVKEY_TMPL_SIZE to 6 for accommodating CKA_DERIVE attribute.
##Checklist
> Increased size of EC_PRIVKEY_TMPL_SIZE

- src/asymmetric_cipher.c
- tests/tlsctx.c
Hi,
Sorry to have closed the previous pull request in which was the explanation of the issue :
https://github.com/latchset/pkcs11-provider/pull/438
So, I've created a new one PR in which I have modified and validated tests (specially the test "pkcs11-provider:softokn/tls" who failed in the previous PR : "49/58 pkcs11-provider:softokn / tls               OK              1.20s."
I also based my modifications on the latest commit on main branch and DCO Signed Off the commit (amend in my case).
Hope everything is OK to merge this correction on the main branch.
Let me know if you need more information.
Thanks.
Sébastien ANDERT
[root@abd701c306ad pkcs11-provider_PKCS11_Crypt2Pay_Compliant]# meson test -C builddir
ninja: Entering directory …
> fix: p11prov_tls_constant_time_depadding bug corrected

- src/keymgmt.c
- src/objects.c
- tests/timported
- tests/ttls
- tests/util.c
Various fixes to issues I found while trying to understand what is going on with #266
> Sundry fixes

- .github/workflows/integration.yml
- tests/integration/bind.sh
- tests/integration/httpd.sh
Changes:
1. Adds support for all three tokens to bind integration test (re-using already present init scripts to test tokens).
2. Disables early initialization quirk for both bind and httpd tests.
3. Updates integration tests actions by adding kryoptic setup, bind test is currently only enabled for kryoptic since bind bug (https://bugzilla.redhat.com/show_bug.cgi?id=2277997) prevents it from running with softokn or softhsm successfully
Fixes #266 
N/A
> Integration test improvements (bind with kryoptic and disabling early initialization)

- src/objects.c
This commit adds **CK_P11PROV_IMPORTED_HANDLE** argument while creating mock public key session object.
Before this patch, when we run TLS1.3 connection, below issue was reported by openssl:-
```
tls_parse_ctos_key_share:unable to find ecdh
parameters:ssl/statem/extensions_srvr.c:684
```
It is because of returning **CK_INVALID_HANDLE** instead of **obj->handle**.
> Passing CK_P11PROV_IMPORTED_HANDLE while creating mock public key

- docs/provider-pkcs11.7
- docs/provider-pkcs11.7.md
- src/debug.c
- src/signature.c
- tests/setup.sh
- tests/softhsm-init.sh
- tests/softokn-init.sh
- tests/test-wrapper
- tests/ttls
This is rebase of previously closed PR #427, which adds also a test reproducer for #449.
This is trying to solve few issues:
* The standard error is not recorded in the log files, which makes them hard to use for debugging
* The expect script `default` does not catch `eof`, which makes some failures hidden
* One of these failures happens in the client, when the provider is forced to be used, but it dies on verification failure. This is because the SSL/TLS code picks up errors left on stack that were not cleaned in several occasions
* The error from reproducer from #449 was also being hidden because the server closed the connection.
* The TLS tests when the provider is forced to be used were executing only one basic use case. This again attempts to run all of them.
* The query for …
> tests: Run more TLS tests when forcing all server operations on token

- docs/provider-pkcs11.7
- docs/provider-pkcs11.7.md
Fixes #361
Add docs for PEM URIs
> Add documentation for URIs in PEM files

- src/session.c
- tests/meson.build
- tests/setup.sh
- tests/tpinlock
For tokens that properly report the status of the PIN authentication counter via token flags, check them out and refuse to attempt login if the token is on its last try.
A token should never be on its last try and finding this flags set is an indication that someone may have hardocded an in correct pin in the configuration or an URI. Proceeding would have a high chance of ending up blocking the token.
Fixes: #455
> Add code to prevent locking the token by mistake

- src/slot.c
In case we have slots advertized but the driver fails to return information or the token is not present we were leaking memory as the slot is not added to the array and the number of slots is not incremented.
Ensure the slot struct is freed in this case.
Fixes #462
> Fix memory leaks when tokens are missing

- .reuse/dep5
- src/keymgmt.c
- src/objects.c
- tests/cert.json.in
- tests/cert.json.part.in
- tests/ttls
- tests/ttlsfuzzer
It turned out the import of EdDSA keys went through the ECDSA code paths which failed down the road. After fixing that, the TLS tests turned out to go into infinite recursion in softhsm where the softhsm operation would call back to the pkcs11 provider code making everything explode. The workaround is to use the propquery on the openssl tools cli, which looks like working ok.
Fixes #461.
> Support TLS operation with EdDSA keys

- src/provider.c
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2327985
> Fix memory leak of ctx_pool.contexts

- .github/workflows/integration.yml
- .github/workflows/kryoptic.yml
- tests/meson.build
Follow-up to #471. The address sanitizer should catch memory leaks, but it needs the configuration, which was missing
https://clang.llvm.org/docs/LeakSanitizer.html
> tests: Use LeakSanitizer to catch future memory leaks

- .github/workflows/build.yml
It seems Homebrew switched to the pkgconf implementation, but this causes a brew link step to fail.
- ~~Test suite updated with functionality tests~~
- ~~Test suite updated with negative tests~~
- ~~Documentation updated~~
> ci: Fix macOS CI

- .reuse/dep5
- packaging/sbom.cdx.json
Hi,
My name is Richard Hughes and I'm a developer at Red Hat. I'm the maintainer of fwupd and LVFS, and am trying to improve software supply chain security by encouraging OEMs, ODMs and IBVs to ship Software Bill of Materials with each firmware binary blob (SBOMs).
I'm working alongside lots of other companies proactively trying to do the right thing. The reason I've opened this pull request is because your project is either used in the *build process* of a firmware we care about (e.g. EDK II, or coreboot) or is built *into the firmware binary* itself. Although my personal focus is on firmware, the SBOM file is in CycloneDX format (one of the most popular industry standards) which makes it also useful when building containers or OS images too.
I would like to contribute this template SBOM …
> Add a SBOM template in CycloneDX format

- tests/cert.json.ecdsa.in
- tests/setup.sh
- tests/tcerts
- tests/ttlsfuzzer
Follow up from #488, where we found the tlsfuzzer has problems with heterogeneous CA + server keys. This creates separate EC key outside of the main CA chain (EC Peer key used for ECDH generally), which turned out to be easier than I expected. It also simplifies the setup a bit and removes the excluded test cases, that should be working.
> tests: Create separate self-signed EC key for tlsfuzzer testing

- BUILD.md
Minor typo fix in BUILD.md - at least that's where the pkgconfig is located on custom OpenSSL build...
> Fix pkgconfig location in BUILD.md

- .github/workflows/build.yml
- meson_options.txt
- tests/meson.build
- tests/setup.sh
- tests/tecxc
This PR adds a meson option to disable explicit EC keys tests.
> Add meson option to disable explicit EC keys tests

- src/encoder.c
- src/objects.c
- src/signature.c
- tests/setup.sh
- tests/tedwards
- tests/tgenkey.c
- tests/tsession.c
There was a logic error in creating the eddsa signature params for pkcs11, that when `OSSL_SIGNATURE_PARAM_INSTANCE` OSSL_PARAM was not provided, the pkcs11 parameters were not created and Ed448 operations were failing.
For some reason, the pkcs11 parameters are required for the Ed448 even if no prehashing nor context is used.
Additionally, if only the context is provided by OpenSSL/caller, we also need to provide the correct parameters, which was not handled before.
Unfortunately, this is not the issue I was after during last days.
> Some fixes for EdDSA signatures + test coverage

- src/exchange.c
Bugfix for OpenSC PKCS#11 provider compatibility.
OpenSC PKCS#11 module fail C_DeriveKey operations with CKR_TEMPLATE_INCOMPLETE error code when used with PKCS#15 smart cards unless CKA_TOKEN attribute is set on the request template. Fix by always requesting session keys (CKA_TOKEN=false). This is also supposed to be the default by PKCS#11 v3.1 - thus not changing the existing behavior.
Current test suite does not address the issue, as the subject failure depends on the  underlying PKCS#11 module, and the cryptographic token used, thus no changes on tests.
> Fixes latchset/pkcs11-provider#502 Explicitly request EcDH derive return key as a session object

- tests/meson.build
- tests/tlsctx.c
- tests/trsapssam
For some reason, with the kryoptic backend we are not getting all the same
errors, but this one is common.
There is also one warning that I missed in the previous PR
> Enable RSA-PSS with ALLOWED_MECHANISMS tests for kryoptic

- meson.build
- meson_options.txt
fix https://github.com/latchset/pkcs11-provider/issues/510
> meson: add option to allow override default default_pkcs11_module

- .github/workflows/build.yml
We build on Mac OS X just to ensure the code builds, however we do not absolutely need to run multiple tests, as functionality with the various tokens is already tested in the rest of the CI
Given lately MAc OS X 14 + SoftHSM always times out, disable it from the matrix for now.
Note that the rest of the conditionals are intentionally preserved, so that we can simply re-add sofhtsm to the matrix should we want to.
Resloves #515
> Drop SoftHSM from the matrix for now

- docs/provider-pkcs11.7
- docs/provider-pkcs11.7.md
```
I: pkcs11-provider: typo-in-manual-page "Allows to" "Allows one to" [usr/share/man/man7/provider-pkcs11.7.gz:112]
I: pkcs11-provider: typo-in-manual-page "Allows to" "Allows one to" [usr/share/man/man7/provider-pkcs11.7.gz:185]
I: pkcs11-provider: typo-in-manual-page "allow to" "allow one to" [usr/share/man/man7/provider-pkcs11.7.gz:63]
I: pkcs11-provider: typo-in-manual-page "allows to" "allows one to" [usr/share/man/man7/provider-pkcs11.7.gz:5]
I: pkcs11-provider: typo-in-manual-page follwing following [usr/share/man/man7/provider-pkcs11.7.gz:266]
```
> docs: fix some typos flagged by Lintian

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- .github/workflows/integration.yml
- .github/workflows/kryoptic.yml
- packaging/pkcs11-provider.spec
- tests/helpers.sh
- tests/lsan.supp
- tests/meson.build
- tests/openssl.cnf.in
- tests/setup.sh
- tests/tcerts
- tests/test-wrapper
- tests/tpinlock
- tests/ttls
- tests/ttlsfuzzer
The openssl command is sufficient to generate and sign all the certs we need for the tests, so drop the use of certtool which reduce our dependency graph for building and testing
Fixes #481
> Drop use of certtool from setup

- tests/ttlsfuzzer
OpenSSL 3.5 added PQC signature algorithms and we need to update tlsfuzzer test to actually expect them from openssl. Also, this PR replaces previous if-then-else block for SIGALGS so that it checks openssl version instead of linux distro. Currently we have 3.0 in ubuntu, 3.2 in fedora and 3.4 in debian. However, our testsuite is also running in openssl CI where upstream version of openssl is used (3.5 now).
N/A
> tests: make tlsfuzzer tests compatible with openssl-3.5

- src/objects.c
Minor formatting change so running `clang-format -i src/object.c` works fine.
> Fix CS in p11prov_obj_pool_free

- src/debug.c
This PR adds a configurable time entry to the debug log. The first commit adds it as disable by default and the second one enables it by default (option can still be used to disable it in that case). I find it more useful to have time there as my use case involved correlation with other logs. But I understand if you prefer not to have it enabled by default. In such case I will remove the second commit.
> Debug logs time

- src/keymgmt.c
- src/objects.c
- src/provider.c
- src/session.c
- src/slot.c
This adds some debug logs that I have been using for debugging various issues with pkcs11-proxy. There are no changes in logic (except some renaming so logging can happen after the locked section). It is quite useful to see how the objects are getting to the pool which also uncovered one issue in the provider (different PR will be created for that).
I'm of course happy to remove the ones that you don't find useful - basically just trying to minimize the diff for my branch.
> Debug logs extra

- .github/workflows/integration.yml
- .github/workflows/kryoptic.yml
The DNF changed location of the  cache files in Fedora so the caching of metadata and downloads did not work. Same issue and fix as in latchset/kryoptic#167.
> ci: Fix DNF caching

- .github/workflows/distcheck.yml
- packaging/pkcs11-provider.spec
Enable gpgcheck by default for downstream builds (so it is not forgotten) but disable it in the ci as we do not have signed tarballs.
--
> packaging: Enable gpgcheck by default for downstream builds

- src/objects.c
- tests/tfork.c
- tests/tpkey.c
- tests/util.c
- tests/util.h
OpenSSL assumes you can create a new EC key by copy the domain parameters from a peer key first (to establish a compatible key type for operations like ECDH), and only later generates the private key material.
Better identify those keys by assigning the CKO_DOMAIN_PARAMETER class to them once parameters are set. We do not have a fully formed key at this point but we already have a bunch of parameter set so this also allows to make decisions on what should or should not be changed anymore at this point. (for example this now will prevent re-importing other parameters over the key).
Fixes #543
> Correctly handle some aspects of key import

- .github/workflows/build.yml
- tests/setup.sh
- tests/softokn-init.sh
- tests/tcms
- tests/tecdh
- tests/thkdf
- tests/ttls
In CI we have tests running when OpenSSL is in FIPS mode. This extends FIPS testing to NSS softokn as wll. There are four tests that need to be skipped for NSS softokn in FIPS mode - ecdh, hkdf, tls and cms. They are doing the key derivation and softokn has additional restrictions in FIPS for it.
> tests: extend FIPS mode to NSS softokn

- .github/workflows/shellcheck.yml
- Makefile
- src/objects.c
- tests/setup.sh
- tests/tbasic
The #547 describes an issue that since 16b491c  the reading of public RSA keys prompts for a PIN. This is due to search for allowed mechanisms on associated private key, which is done in any case the public key does not have allowed_mechanisms attribute.
This PR has a reproducer for #547 and a partial fix for tokens not supporting allowed mechanisms.
For the remaining, it will likely need some more digging or workaround as we should login if the pin is provided by some means, but we should not if it is not. I did not manage to express this yet in the code.
> Prevent login prompt when reading public RSA keys

- .github/workflows/openssl.yml
This tests provider build and it tests (for softokn and softhsm tokens) when openssl is built from its git master branch. It caches openssl installation in /opt directory and the cache is valid for one day.
> CI: Add testing with OpenSSL master branch

- .github/workflows/openssl.yml
Cache actions only caches when job succeeds and since we can expect CI tests to fails during the development work OpenSSL built in /opt might not get cached during multiple executions within the same PR.
Separating openssl build into its own job make it always succeed and cache is stored even if the tests from the second job fails.
> CI: split openssl action into two jobs

- .github/workflows/distcheck.yml
- tests/integration/libssh.sh
Some time ago, I wrote the tests for libssh to use Ed25519 keys from pkcs11-provider:
https://gitlab.com/libssh/libssh-mirror/-/merge_requests/558
But it looks like the integration tests explicitly select just the tree tests that were here before so the new one was never picked up. This adjusts the regex to match all the pkcs11 uri tests in libssh testsuite
In libssh tests this one test is failing though (unexpectedly prompting for pin interactively)  so I am trying to figure out what is going on there and if the libssh or pkcs11-provider needs a fix. We need to extend this coverage anyway though.
> Run all pkcs11 tests from libssh

- tests/kryoptic-init.sh
- tests/setup.sh
The environment variables was needed only for the certtool, which was removed in d681a1abe244ba08a62498ab4da8b0351f5b40f1 some months ago.
> Remove unused environtment variables

- .github/workflows/build.yml
- meson.build
- tests/cert.json.ecdsa.in
- tests/cert.json.ed25519.in
- tests/cert.json.ed448.in
- tests/cert.json.in
- tests/cert.json.rsa.in
- tests/cert.json.rsapss.in
- tests/helpers.sh
- tests/setup.sh
- tests/tbasic
- tests/tdemoca
- tests/ttls
- tests/ttlsfuzzer
This modifies the meson script to look for alternative libcrypto/libssl package names so correct ones are found on RHEL 8 where the original names represent the OpenSSL 1.1 line and hence are not picked by meson. However OpenSSL 3 packages can be installed from the EPEL repository side-by-side with package names ending with `3` (e.g. libcrypto3).
See https://github.com/latchset/pkcs11-provider/discussions/570
> Allow build on RHEL 8

- .github/workflows/build.yml
- src/objects.c
- src/provider.c
- tests/meson.build
- tests/setup.sh
- tests/tecdh
- tests/tecx.c
- tests/tecxc
- tests/util.c
Fix EC params import for Explicit EC Keys, which broke CMS operations.
Add tests to avoid future regressions, enable ECDH tests for SoftHSM2 where possible.
Changes how some tests are run in CI to test more cases even when some tests are known fails on some platforms (eg TLS tests on Debian with SoftHSM2).
#562
> Ensure CMS with Explicit EC works

- src/slot.c
Do not require CKF_USER_PIN_INITIALIZED top be set for default slot.
Fixes #569
> Fine tune how default slot is selected

- .github/workflows/coverity-scan.yml
- BUILD.md
- meson.build
- meson_options.txt
- src/provider.c
Fixes #576
Sets C macros for P11PROV_VERSION taken from meson's project version and P11PROV_BUILDINFO which is set from the meson option named "build_info". If this option is empty the build info string is set to
"Built with OpenSSL version <ver>" where <ver> is the version of OpenSSL used for headers at built time during compilation.
> Add proper version and build info to provider

- .github/workflows/coverity-scan.yml
The last PR had a mistake in the covscan script, but because we have "pull_request_target" (due to the use of secrets) the actual change was not tested.
This PR is pushed on a branch in the main repo so that we can test the PR before merging.
> Fix covscan checks

- src/encoder.c
The variables keypoint, pubkey, nid, and ret are unused when NID_ML_DSA_44 is not defined, and so is the
p11prov_mldsa_set_keypoint_data function.
> Fix warnings when building against older OpenSSL

- src/keymgmt.c
- src/objects.c
- src/objects.h
- src/provider.h
- src/skeymgmt.c
... and deal wit it using `p11prov_common_load` 
A counterpart to https://github.com/openssl/openssl/pull/28278
Superseds #618
> We already have the P11PROV_OBJ* we need

- .github/workflows/build.yml
- .github/workflows/openssl.yml
- src/cipher.c
- src/util.h
- ~[ ] Code modified for feature~
- ~[ ] Test suite updated with negative tests~
> Add a couple of tests to build on ARM-64

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- .github/workflows/coverity-scan.yml
- .github/workflows/distcheck.yml
- .github/workflows/integration.yml
- .github/workflows/kryoptic.yml
- .github/workflows/openssl.yml
- .github/workflows/scan-build.yml
- .github/workflows/style.yml
- src/asymmetric_cipher.c
- src/cipher.c
- src/encoder.gen.c
- src/exchange.c
- src/interface.c
- src/interface.gen.c
- src/interface.h
- src/interface.pre
- src/kdf.c
- src/objects.c
- src/objects.h
- src/pk11_uri.gen.c
- src/session.c
- src/session.h
- src/sig/internal.h
- src/sig/signature.c
- src/skeymgmt.c
This patchset comes out of a review oh how sessions are used after the EVP_SKEY facilities introduction.
One of the things I notices was that we had overly complicated code around handling two items on the session pool, login_session and open_sessions. Manipulating these attributes required, potentially costly, locking of pools every time a session is taken.
Additionally I noticed that in repeat operations session could be passed around which is not optimal on tokens that cache or otherwise internally tie ephemeral keys to sessions.
By adding a simple reference counter that prevents session from being closed and saving a pointer to those sessions on objects that have been created, it was possible to remove a bunch of locking and simplify other calls.
All this also ensures that ephemeral …
> Improve session handling

- docs/provider-pkcs11.7
- docs/provider-pkcs11.7.md
The markdown requires the list are preceded by an empty line. Without this, the manual page lists are not rendered correctly
> doc: Render markdown lists
