latchset/pkcs11-provider

- .gitignore
- Makefile.am
- configure.ac
Update some obsolete macros, add missing macros and enable
automake to report all warnings and bail-out on warnings.
> Modernize the autotools usage a bit

- src/provider.c
- src/provider.h
- src/store.c
- tests/openssl.cnf.in
- tests/test.sh
> Add handling of pin in provider configuration

- src/store.c
Allows openssl utils or any application to prompt for the pin when needed and not otherwise available.
> Add PIN prompting support

- src/asymmetric_cipher.c
- src/debug.c
- src/exchange.c
- src/kdf.c
- src/keymgmt.c
- src/keys.c
- src/provider.c
- src/provider.h
- src/signature.c
- src/store.c
- src/util.c
Use atomics to check if debug is enabled and init the debugging system
> Make debug functions a little more robust

- src/provider.c
- src/store.c
- src/util.c
Various issues fixed found by valgrind during test suite running.
> Fix issues found by valgrinding test suite

- src/keymgmt.c
- src/keys.c
One moderate potential out of bounds issues, and the general printf format specifier issues.
> New batch of coverity findings after the last few merges

- src/debug.c
- src/keymgmt.c
- src/provider.c
- src/provider.h
- src/store.c
This provides a complete list of all the supported mechanisms.
It also select the available operations based on the token stated mechanism availability.
> Add code to list and debug token mechanisms

- src/provider.c
rsapss PR issues caught by coverity
> Coverity Fixes series 6

- src/debug.c
- src/provider.h
- tests/test.sh
Add debug levels so we can push noisy Mechanism Info debugging to a higher level.
Fix interference with system utilities when manually testing/debugging by renaming TMPDIR to TMPPDIR
> Make debugging less annoying

- .github/scripts/ci.sh
- .github/scripts/run_dockerized.sh
- .github/workflows/build.yml
- configure.ac
This should allow us to use the more recent openssl version we need which is available in Fedora and Debian unstable
> Change CI to run custom distros via containers

- BUILD.md
> Update build prerequisites

- src/signature.c
Some better debug info on parameters and digests
> Improve signature debugging wrt paramter setting

- src/signature.c
This generalizes the code quite a bit and removes copied code.
> Add p11prov_mech_by_mechanism() helper and use it

- src/signature.c
- tests/tbasic
- tests/teccsha2
- Add test for ECDSA verify using openssl algorithm
- Add test for EC/SHA2 CSR
- Add verify for RSA CSR
> Fix ECDSA signatures and improve tests

- .github/ISSUE_TEMPLATE/rfe.md
Add a template to create a Feature Request like we have one for Bugs
> Add guided RFE issue creation

- src/keymgmt.c
We want to store the pubkey on the token too.
> Aligning public and private key generation templates

- configure.ac
Debian stable still have 2.69, and everything works fine
> We can reduce this requirement

- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- tests/Makefile.am
- tests/setup-softhsm.sh
- tests/softhsm-proxy.sh
- tests/tcerts
This extends the setup similarly as it is done with softokn (in #143) now to have certificates on the smart cards.
> Generate certificates for SoftHSM tests

- src/debug.c
- src/debug.h
- src/provider.h
> Simplify debug machinery and print line/function

- .github/workflows/build.yml
- .github/workflows/distcheck.yml
- src/session.c
- src/store.c
- tests/tbasic
While reviewing #167 it was found out that a regression had happened and prompting for a PIN was not working anymore.
Resolve the issue and add tests to prevent future regressions.
Fixes #172
> Fix prompting for PIN

- src/kdf.c
- src/session.c
> Relax state check on login session

- src/session.c
- src/store.c
- tests/tbasic
This commit should address #188
> Change how we determine if login is required

- src/signature.c
Improve setting PSS params defaults.
Calculate defaults based on the digest set, but only if mfg and saltlen have not been explicitly set to different values.
Calculate saltlen also for openssl negative default codes and special strings instead of bailing out.
Fixes #191
> Better PSS params defaults handling

- src/objects.c
> Fix leak of EC_GROUP on error paths

- tests/Makefile.am
- tests/openssl.cnf.in
- tests/setup-softhsm.sh
- tests/setup-softokn.sh
- tests/tdemoca
> Add demoCA tests to test certificate signing

- src/Makefile.am
- src/interface.c
- src/interface.h
- src/objects.c
- src/objects.h
- src/provider.c
- src/provider.h
- src/session.c
- src/session.h
- src/slot.c
- src/slot.h
- src/store.c
- src/util.c
- src/util.h
- tests/Makefile.am
- tests/tfork.c
> Add support to cleanup after fork, and test it

- src/util.c
Also fixed CID 452519
Coverity always very useful to catch silly stuff.
> CID 452520: Copy-paste error

- src/provider.c
- src/provider.h
- src/session.c
- src/session.h
- src/util.c
- src/util.h
This reworks a bit session caching to be a little more resonable and gives the user a way to influence it if needed.
Fixes #169
> Add tunable to influence session caching

- .gitignore
- BUILD.md
- configure.ac
> some setup nits for OpenSSL

- src/provider.c
Prints out the strings as sourced by openssl's helpers and the result of the actual settings after parsing.
> Add debugging of config options

- src/provider.c
- src/signature.c
Assorted fixes from latest run
> Minor coverity fixes

- configure.ac
- src/Makefile.am
> Do not link provider to libssl

- packaging/pkcs11-provider.spec
spec file clean up.
This PR addresses the review comment in https://github.com/latchset/pkcs11-provider/pull/253
> spec file clean up.

- src/keymgmt.c
Fix resource leak, also covers CID 465960
> CID 465959: Resource leaks

- tests/tgenkey.c
> Fix RSA key generation and test size

- configure.ac
- packaging/pkcs11-provider.spec
> Release version 0.3

- SECURITY.md
> Fix minor typo (teplate->template)

- tests/README
- tests/README.md
Resolves: #381
Fix tests/README file (adapt to meson based compilation)
> Fix tests/README (adapt to meson)

- .github/workflows/build.yml
There will be different set of bugs on different distro.
> ci: Run the CI also on ubuntu

- Makefile
- README.md
- meson.build
- packaging/pkcs11-provider.spec
Testing using a PR to kickstart a new release.
Still haven't figure out yet tagging (we used signed tags), but will add that manually on the main branch after merge for now.
> Release version 0.5

- tests/setup.sh
This will help integrating provider self-test into OpenSSL CI.
> tests: get rid of unnecessary redirection

- src/util.c
Subset of #524 that should pass the CI and allow us merging related kryoptic change.
> Fix handling of Invalid attributes

- src/objects.c
1. **Inconsistent BIGNUM Representations:**  
- OpenSSL exports the RSA public exponent (`e = 65537`) into provider  `object->attrs` using a **minimal byte representation** (`3` bytes: `0x01 00 01`).  
- AWS CloudHSM returns the same exponent value (`65537`), but it is stored as **8 bytes** (`0x01 00 01 00 00 00 00 00`).  
2. **Memory Comparison Issue in `cmp_attr`:**  
- The function `cmp_attr(pub_key1, pub_key2, CKA_PUBLIC_EXPONENT)` **fails** because it performs a **raw memory comparison**.  
- Due to different encodings (**3 bytes vs. 8 bytes**), the function incorrectly treats identical values as different.  
For attributes representing numeric values (e.g., `CKA_PUBLIC_EXPONENT`, `CKA_MODULUS`):  
Compare values using **`BN_cmp()`** instead of a raw memory comparison.
> FIX: Compare attributes of type bignum as native-endian bignum

- .github/workflows/address-sanitizer.yml
- .github/workflows/build.yml
- .github/workflows/coverity-scan.yml
- .github/workflows/openssl.yml
- tests/helpers.sh
- tests/integration/httpd.sh
- tests/meson.build
- tests/setup.sh
- tests/softhsm-init.sh
- tests/tskey
- tests/ttlsfuzzer
Test that we can, in fact, disable symmetric key operations.
Fixes #556
> Test disabling symmetric operation for tokens

- COVSCAN.md
Fix covscan workflows and add readme that explains how we fix the covscan wrokflows
Fix also workflow bug that failed to check the PR for changes on rebases when the covscan-ok label is set.
> Fix the Covscan fixes

- src/cipher.c
Return the gettable and settable ctx params we support.
Move setting padding and CTS mode to the set_ctx_params function so that those can be set by a direct set_ctx_param() as well.
Fixes: #583
> AES: better handling of ctx params

- .github/workflows/coverity-scan.yml
New container doesn't have command required by coverity tools
> Fix coverity check container

- src/pkcs11.h
We do not implement this function but let's keep headers up to date with latest fixes
> Fix bug in PKCS#11 header
